version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kku_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres7842
      POSTGRES_DB: kku_scorecard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kku_backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres7842@postgres:5432/kku_scorecard?schema=public"
      PYTHON_EXECUTABLE: /usr/bin/python3
      # AUTH_MODE: SSO
      SSO_APP_ID: 019f5e75-113a-7c95-ae18-04b99b7f653b
      SSO_CLIENT_ID: 019f5e75-113a-7c95-ae18-04b99b7f653b
      SSO_CLIENT_SECRET: NrpTzowwLTDaVJdoBmL9BL78j2s2OxlszoSJVMVfeznBViyN9utvcdCD56MZw9q7
      ADMIN_EMAILS: watchara.sup@kkumail.com
      # NODE_ENV: production
      FRONTEND_URL: https://odt-scorecard.kku.ac.th
      APP_BASE_URL: https://odt-scorecard.kku.ac.th
      SSO_REDIRECT_URL: https://odt-scorecard.kku.ac.th/callback
      SSO_LOGIN_URL: https://sso-uat-web.kku.ac.th/login
      SSO_LOGOUT_URL: https://sso-uat-web.kku.ac.th/logout
      SSO_TOKEN_API: https://sso-uat-api.kku.ac.th/auth.token
      SSO_PROFILE_API: https://sso-uat-api.kku.ac.th/user.profile
      SSO_STATUS_API: https://sso-uat-api.kku.ac.th/auth.status

    volumes:
      - ./python:/app/python:ro
      - backend_data:/app/data
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped
    command: sh -c "npx prisma db push --accept-data-loss && node dist/index.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ""
    container_name: kku_frontend
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4000
#    ports:
#      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: kku_nginx
    ports:
      - "4333:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:
  backend_data:

networks:
  app_network:
    driver: bridge
